version: '3.8'

services:
    ### 🔹 MySQL Database ###
    mysql:
        image: mariadb:10.3
        container_name: mysql
        restart: always
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: fruit
            MYSQL_ROOT_PASSWORD: root
           MYSQL_USER: root
            MYSQL_PASSWORD: root

    ### 🔹 phpMyAdmin ###
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: phpmyadmin
#        restart: always
#        environment:
#            PMA_HOST: mysql
#            PMA_PORT: 3306
#        ports:
#            - "8080:80"
#        depends_on:
#            - mysql

    ### 🔹 Laravel Backend (API) ###
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fruit-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        ports:
            - "8000:8000"
        environment:
            APP_ENV: local
            APP_KEY: base64:randomkey
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: fruit
            DB_USERNAME: root
            DB_PASSWORD: root
        command: php artisan serve --host=0.0.0.0 --port=8000

    ### 🔹 Vue.js Frontend ###
    frontend:
        build:
            context: .
            dockerfile: frontendDockerfile
        container_name: fruit-frontend
        restart: unless-stopped
        ports:
            - "5173:5173"
        volumes:
            - .:/app
        depends_on:
            - backend
        command: npm run dev -- --host 0.0.0.0

volumes:
    mysql_data:
